#!/bin/bash

function deploy_to
{
    typeset host="$1"
    typeset path="$2"
    typeset cd="$3"

    debug="true"
    debug="set -x"
    echo "Creating new-snapper on ${host}"
    sed \
    	-e "1s%.*%#!$path%" \
    	-e "s/%%% VERSION %%%/${version}/" \
    	-e "s/%%% RELEASE %%%/${release}/" \
    	snapper.rb > /tmp/snapper.rb
    chmod +x /tmp/snapper.rb

    tar cf - News bos_vrmf_map lib issues.rb -C /tmp snapper.rb | gzip -9 | \
    	ssh ${host} "$debug && \
                     cd $cd && \
                     rm -rf new-snapper && \
                     mkdir new-snapper && \
                     cd new-snapper && \
                     gunzip | tar xf -"
    echo "Fixing permissions"
    ssh ${host} "$debug && cd $cd && chmod -R go=u,o-w new-snapper"
    echo "Moving new snapper into place on ${host}"
    ssh ${host} "$debug && cd $cd && rm -rf old-snapper && mv snapper old-snapper && mv new-snapper snapper"
    echo "Moving or creating log file into place on ${host}"
    ssh ${host} "$debug && cd $cd && touch old-snapper/log && chmod 666 old-snapper/log && mv old-snapper/log snapper/log"
}

describe="$( git describe )"

# If there are no '-', we are at a "gold" release ;-)
if [[ $describe == *-* ]] ; then
    tag="${describe%%-*}"
    other="${describe#*-}"
    minor="${other%%-*}"
    hash="${other#*-}"
    # echo "$tag"
    # echo "$other"
    # echo "$minor"
    # echo "$hash"
    version="${tag%.*}.${minor}"
    release="${hash}"
else
    version="${describe}"
    release="gold"
fi

echo "Deploying ${version} (${release})"

rake clean-docs; rake all-docs
deploy_to aixbd01 /shared/pedzan/ruby-2.2.3/bin/ruby /shared/pedzan
